### ISSUE TITLE
FromHID() needs to be changed to OpenDevice() in PowerShell example

### ISSUE THREAD

**Issue by imorrish** [OpenStreamDeck/StreamDeckSharp#5]
Just found this out when updating to a more recent version.
In the PowerShell example it should now be
$deckInterface = [StreamDeckSharp.StreamDeck]::OpenDevice()

Can also use some of the other new graphics methods
$imgRed = [StreamDeckSharp.KeyBitmap]::FromRGBColor([byte]255,[byte]0,[byte]0)
$deckInterface.SetKeyBitmap(0, $imgRed)

I have a sample for controlling Blackmagic ATEM with program/preview live image updates here
https://github.com/imorrish/VISE_Scripts/tree/master/Stream%20Deck

**Comment by wischi-chr** [comment]
Hi Ian.
I apologize for my late response. I'm not very experienced with PowerShell and sadly can't keep that up to date on my own. I changed the wiki settings so you should be able edit pages.

Feel free to edit/add pages and you can add the link(s) to your projects as well.

Let me know if that works for you ;-)
